################################### Default Configuration ############################
baseurl = "/"
title = "LoSpeziale"
theme = "vex-hugo"
# post excert
summarylength = "20"
# google analytics
googleAnalytics = "" # Ex: UA-123-45
# disable language
disableLanguages = [] # disable language from here
defaultContentLanguage = "it"

# unsafe html
[markup.goldmark.renderer]
unsafe = true

#################################### Plugins ##########################################

# CSS Plugins
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,400,600,700|Amatic+SC:300,400,600,700"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themefisher-font/themefisher-font.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.min.css"
[[params.plugins.css]]
link = "https://cdn.snipcart.com/themes/v3.0.27/default/snipcart.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "https://cdn.snipcart.com/themes/v3.0.27/default/snipcart.js"


###################################### Navigation ######################################

# homepage section menu
[[Languages.en.menu.main]]
name = "Home"
url = "/"
weight = 1

[[Languages.en.menu.main]]
name = "Products"
url = "products"
weight = 2

[[Languages.en.menu.main]]
name = "Blog"
url = "blog"
weight = 3

[[Languages.en.menu.main]]
name = "Review"
pre = "#"
url = "testimonial"
weight = 4

[[Languages.en.menu.main]]
name = "Contact"
url = "contact"
weight = 5

# footer menu
[[Languages.en.menu.footer]]
name = "Blog"
url = "blog"
weight = 1

[[Languages.en.menu.footer]]
name = "Contact"
url = "contact"
weight = 2

[[Languages.en.menu.footer]]
name = "Terms & Conditions"
url = "terms-conditions"
weight = 3

[[Languages.en.menu.footer]]
name = "Privacy Policy"
url = "privacy-policy"
weight = 4


############## IT #####################
[[Languages.it.menu.main]]
name = "Home"
url = "/"
weight = 1

[[Languages.it.menu.main]]
name = "Prodotti"
url = "products"
weight = 2

[[Languages.it.menu.main]]
name = "Blog"
url = "blog"
weight = 3

[[Languages.it.menu.main]]
name = "Recensioni"
pre = "#"
url = "testimonial"
weight = 4

[[Languages.it.menu.main]]
name = "Contatti"
url = "contact"
weight = 5

# footer menu
[[Languages.it.menu.footer]]
name = "Blog"
url = "blog"
weight = 1

[[Languages.it.menu.footer]]
name = "Contatti"
url = "contact"
weight = 2

[[Languages.it.menu.footer]]
name = "Termini e Condizioni"
url = "terms-conditions"
weight = 3

[[Languages.it.menu.footer]]
name = "Privacy Policy"
url = "privacy-policy"
weight = 4


########################### Default parameters ##########################
[params]
logo = "images/logo.png"
logo_width = "200px"
# Meta data
description = "This is meta description"
author = "Themefisher"
# currency
currency = "€"
# contact form action
contact_form_action = "https://formspree.io/f/mayawddo" # contact form works with https://formspree.io
# snipcart public api key
snipcart_api = "ZDgxY2ZiM2EtMWRmMi00M2ZkLWI1MDAtNzA2MDc0Y2Q1MzJlNjM3MTAzNDIwOTQ1NDA4NjM4"

# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

# Subscription
[params.subscription]
# mailchimp subsciption
mailchimp_form_action = "https://tinyletter.com/lospeziale" # replace this url with yours
contact_email = "telespallabob07@gmail.com"

################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en"
contentDir = "content/english"
weight = 2
# copyright
copyright = "Designed By [Themefisher](https://themefisher.com/) & Developed By [Gabriele Orazi](https://goemon07.github.io/)"


################################### Italian language #####################################
[Languages.it]
languageName = "It"
languageCode = "it"
contentDir = "content/italian"
weight = 1
# copyright
copyright = "Designed By [Themefisher](https://themefisher.com/) & Developed By [Gabriele Orazi](https://goemon07.github.io/)"